FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PORT=10000

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Future production command:
CMD ["sh", "-c", "python manage.py setup_project --full-auto && gunicorn backend.wsgi:application --bind 0.0.0.0:${PORT:-10000} --workers ${GUNICORN_WORKERS:-3}"]
#CMD ["sh", "-c", "python manage.py setup_project --full-auto && python manage.py runserver 0.0.0.0:${PORT:-10000}"]

EXPOSE 10000
