# Generated by Django 5.2.8 on 2026-05-11 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('normal_arena_anonymous_per_minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal_arena_anonymous_per_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal_arena_anonymous_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal_arena_user_per_minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal_arena_user_per_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('normal_arena_user_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('experimental_arena_user_per_minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('experimental_arena_user_per_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('experimental_arena_user_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('chat_user_per_minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('chat_user_per_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('chat_user_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(choices=[('normal_arena_anonymous', 'Normal Arena Anonymous'), ('normal_arena_user', 'Normal Arena User'), ('experimental_arena_user', 'Experimental Arena User'), ('chat_user', 'Chat User')], max_length=40)),
                ('identity_type', models.CharField(choices=[('ip', 'IP'), ('user', 'User')], max_length=8)),
                ('identity', models.CharField(max_length=255)),
                ('window', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], max_length=12)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['bucket', 'identity_type', 'identity'], name='platform_se_bucket_905982_idx'), models.Index(fields=['window_start'], name='platform_se_window__b46f88_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'identity_type', 'identity', 'window', 'window_start'), name='unique_rate_limit_usage_window')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('rate_limits', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='platform_settings', to='platform_settings.ratelimits')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='platform_se_is_acti_a26a7a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_platform_settings')],
            },
        ),
    ]
