# Generated by Django 5.2.8 on 2026-04-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_arena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSamplingSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_name', models.CharField(choices=[('temperature', 'Temperature'), ('top_p', 'Top P'), ('top_k', 'Top K'), ('frequency_penalty', 'Frequency Penalty'), ('presence_penalty', 'Presence Penalty')], max_length=32, unique=True)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer')], max_length=16)),
                ('minimum_value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('maximum_value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('uniform_min', models.DecimalField(decimal_places=4, max_digits=8)),
                ('uniform_max', models.DecimalField(decimal_places=4, max_digits=8)),
                ('normal_mean', models.DecimalField(decimal_places=4, max_digits=8)),
                ('normal_std', models.DecimalField(decimal_places=4, max_digits=8)),
                ('beta_alpha', models.DecimalField(decimal_places=4, max_digits=8)),
                ('beta_beta', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'ordering': ['parameter_name'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_mode', models.CharField(choices=[('same_model', 'Same Model'), ('different_models', 'Different Models')], max_length=24)),
                ('share_values_across_models', models.BooleanField(blank=True, null=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_config', to='llm_arena.arenabattle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrequencyPenaltyExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution', models.CharField(choices=[('uniform', 'Uniform'), ('normal', 'Normal'), ('beta', 'Beta')], max_length=16)),
                ('value_a', models.DecimalField(decimal_places=4, max_digits=6)),
                ('value_b', models.DecimalField(decimal_places=4, max_digits=6)),
                ('experiment_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_penalty_config', to='experimental_llm_arena.experimentconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresencePenaltyExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution', models.CharField(choices=[('uniform', 'Uniform'), ('normal', 'Normal'), ('beta', 'Beta')], max_length=16)),
                ('value_a', models.DecimalField(decimal_places=4, max_digits=6)),
                ('value_b', models.DecimalField(decimal_places=4, max_digits=6)),
                ('experiment_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence_penalty_config', to='experimental_llm_arena.experimentconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution', models.CharField(choices=[('uniform', 'Uniform'), ('normal', 'Normal'), ('beta', 'Beta')], max_length=16)),
                ('value_a', models.DecimalField(decimal_places=4, max_digits=6)),
                ('value_b', models.DecimalField(decimal_places=4, max_digits=6)),
                ('experiment_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_config', to='experimental_llm_arena.experimentconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopKExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution', models.CharField(choices=[('uniform', 'Uniform'), ('normal', 'Normal'), ('beta', 'Beta')], max_length=16)),
                ('value_a', models.PositiveIntegerField()),
                ('value_b', models.PositiveIntegerField()),
                ('experiment_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_k_config', to='experimental_llm_arena.experimentconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopPExperimentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution', models.CharField(choices=[('uniform', 'Uniform'), ('normal', 'Normal'), ('beta', 'Beta')], max_length=16)),
                ('value_a', models.DecimalField(decimal_places=4, max_digits=6)),
                ('value_b', models.DecimalField(decimal_places=4, max_digits=6)),
                ('experiment_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_p_config', to='experimental_llm_arena.experimentconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
